version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: eventscheduler
      POSTGRES_USER: event
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  event-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/eventscheduler
      SPRING_DATASOURCE_USERNAME: event
      SPRING_DATASOURCE_PASSWORD: 123

volumes:
  postgres_data: